<?php

namespace Game\CardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    /*
     * Retourne la dernière partie jouée
     */
    public function findLast()
    {
        $queryBuilder = $this->_em->createQueryBuilder('g')
            ->select('g')
            ->from($this->_entityName, 'g')
            ->orderBy('g.id', 'DESC')
            ->setMaxResults(1);
        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
