<?php

namespace Game\CardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findLast()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('g, MAX(g.id), g.scoreA, g.scoreB')
            ->from($this->_entityName, 'g');
        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
