game_card_homepage:
    path:     /
    defaults: { _controller: GameCardBundle:Default:index }

game_card_player:
    path:     /player/
    defaults: { _controller: GameCardBundle:Player:index }

game_card_player_show:
    path:     /player/show/{id}
    defaults: { _controller: GameCardBundle:Player:show }
    requirements:
        id: \d+

game_card_team:
    path:     /team/
    defaults: { _controller: GameCardBundle:Team:index }

game_card_game:
    path:     /game/
    defaults: { _controller: GameCardBundle:Game:index }

game_card_rule:
    path:     /rule/
    defaults: { _controller: GameCardBundle:Default:rule }