parameters:
    manager.statistic.class: Game\CardBundle\Manager\StatisticManager

services:
   manager.statistic:
       class: %manager.statistic.class%
       arguments: ["@doctrine.orm.entity_manager"]
