<?php

namespace Game\CardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function myFindAll()
    {
        $queryBuilder = $this->_em
            ->createQueryBuilder('t')
            ->select('t')
            ->from($this->_entityName, 't');

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
